name: Dist
on:
  push:
    branches:
      - "release/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
      # update apt cache
      - name: Update apt cache
        run: sudo apt-get update -y
      # Set node version
      - uses: actions/setup-node@v2
        with:
          node-version: "14.21.3"
      - name: Set NPM 7
        run: npm install -g npm@8.19.4
      # Cache node_modules
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install MDNS build dependencies
        run: sudo apt-get install libavahi-compat-libdnssd-dev

      - name: Install node modules
        run: npm install

      - name: Linux build
        run: npm run dist:linux -- --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
